/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Listings } from "./Listings";
import { ListingsCountArgs } from "./ListingsCountArgs";
import { ListingsFindManyArgs } from "./ListingsFindManyArgs";
import { ListingsFindUniqueArgs } from "./ListingsFindUniqueArgs";
import { CreateListingsArgs } from "./CreateListingsArgs";
import { UpdateListingsArgs } from "./UpdateListingsArgs";
import { DeleteListingsArgs } from "./DeleteListingsArgs";
import { OrdersFindManyArgs } from "../../orders/base/OrdersFindManyArgs";
import { Orders } from "../../orders/base/Orders";
import { Materials } from "../../materials/base/Materials";
import { ServiceProviders } from "../../serviceProviders/base/ServiceProviders";
import { ListingsService } from "../listings.service";
@graphql.Resolver(() => Listings)
export class ListingsResolverBase {
  constructor(protected readonly service: ListingsService) {}

  async _listingsItemsMeta(
    @graphql.Args() args: ListingsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Listings])
  async listingsItems(
    @graphql.Args() args: ListingsFindManyArgs
  ): Promise<Listings[]> {
    return this.service.listingsItems(args);
  }

  @graphql.Query(() => Listings, { nullable: true })
  async listings(
    @graphql.Args() args: ListingsFindUniqueArgs
  ): Promise<Listings | null> {
    const result = await this.service.listings(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Listings)
  async createListings(
    @graphql.Args() args: CreateListingsArgs
  ): Promise<Listings> {
    return await this.service.createListings({
      ...args,
      data: {
        ...args.data,

        material: args.data.material
          ? {
              connect: args.data.material,
            }
          : undefined,

        serviceProvider: args.data.serviceProvider
          ? {
              connect: args.data.serviceProvider,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Listings)
  async updateListings(
    @graphql.Args() args: UpdateListingsArgs
  ): Promise<Listings | null> {
    try {
      return await this.service.updateListings({
        ...args,
        data: {
          ...args.data,

          material: args.data.material
            ? {
                connect: args.data.material,
              }
            : undefined,

          serviceProvider: args.data.serviceProvider
            ? {
                connect: args.data.serviceProvider,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Listings)
  async deleteListings(
    @graphql.Args() args: DeleteListingsArgs
  ): Promise<Listings | null> {
    try {
      return await this.service.deleteListings(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Orders], { name: "ordersItems" })
  async findOrdersItems(
    @graphql.Parent() parent: Listings,
    @graphql.Args() args: OrdersFindManyArgs
  ): Promise<Orders[]> {
    const results = await this.service.findOrdersItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Materials, {
    nullable: true,
    name: "material",
  })
  async getMaterial(
    @graphql.Parent() parent: Listings
  ): Promise<Materials | null> {
    const result = await this.service.getMaterial(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => ServiceProviders, {
    nullable: true,
    name: "serviceProvider",
  })
  async getServiceProvider(
    @graphql.Parent() parent: Listings
  ): Promise<ServiceProviders | null> {
    const result = await this.service.getServiceProvider(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
