/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsOptional, IsString, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Materials } from "../../materials/base/Materials";
import { Orders } from "../../orders/base/Orders";
import { ServiceProviders } from "../../serviceProviders/base/ServiceProviders";

@ObjectType()
class Listings {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  availableFrom!: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  availableTo!: Date | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => Materials,
  })
  @ValidateNested()
  @Type(() => Materials)
  @IsOptional()
  material?: Materials | null;

  @ApiProperty({
    required: false,
    type: () => [Orders],
  })
  @ValidateNested()
  @Type(() => Orders)
  @IsOptional()
  ordersItems?: Array<Orders>;

  @ApiProperty({
    required: false,
    type: () => ServiceProviders,
  })
  @ValidateNested()
  @Type(() => ServiceProviders)
  @IsOptional()
  serviceProvider?: ServiceProviders | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Listings as Listings };
