/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { MaterialsWhereUniqueInput } from "../../materials/base/MaterialsWhereUniqueInput";
import { OrdersListRelationFilter } from "../../orders/base/OrdersListRelationFilter";
import { ServiceProvidersWhereUniqueInput } from "../../serviceProviders/base/ServiceProvidersWhereUniqueInput";

@InputType()
class ListingsWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  availableFrom?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  availableTo?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MaterialsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MaterialsWhereUniqueInput)
  @IsOptional()
  @Field(() => MaterialsWhereUniqueInput, {
    nullable: true,
  })
  material?: MaterialsWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => OrdersListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OrdersListRelationFilter)
  @IsOptional()
  @Field(() => OrdersListRelationFilter, {
    nullable: true,
  })
  ordersItems?: OrdersListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ServiceProvidersWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServiceProvidersWhereUniqueInput)
  @IsOptional()
  @Field(() => ServiceProvidersWhereUniqueInput, {
    nullable: true,
  })
  serviceProvider?: ServiceProvidersWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;
}

export { ListingsWhereInput as ListingsWhereInput };
