/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsOptional, IsString, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { MaterialsWhereUniqueInput } from "../../materials/base/MaterialsWhereUniqueInput";
import { OrdersCreateNestedManyWithoutListingsItemsInput } from "./OrdersCreateNestedManyWithoutListingsItemsInput";
import { ServiceProvidersWhereUniqueInput } from "../../serviceProviders/base/ServiceProvidersWhereUniqueInput";

@InputType()
class ListingsCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  availableFrom?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  availableTo?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => MaterialsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MaterialsWhereUniqueInput)
  @IsOptional()
  @Field(() => MaterialsWhereUniqueInput, {
    nullable: true,
  })
  material?: MaterialsWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => OrdersCreateNestedManyWithoutListingsItemsInput,
  })
  @ValidateNested()
  @Type(() => OrdersCreateNestedManyWithoutListingsItemsInput)
  @IsOptional()
  @Field(() => OrdersCreateNestedManyWithoutListingsItemsInput, {
    nullable: true,
  })
  ordersItems?: OrdersCreateNestedManyWithoutListingsItemsInput;

  @ApiProperty({
    required: false,
    type: () => ServiceProvidersWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServiceProvidersWhereUniqueInput)
  @IsOptional()
  @Field(() => ServiceProvidersWhereUniqueInput, {
    nullable: true,
  })
  serviceProvider?: ServiceProvidersWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { ListingsCreateInput as ListingsCreateInput };
