/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Orders } from "./Orders";
import { OrdersCountArgs } from "./OrdersCountArgs";
import { OrdersFindManyArgs } from "./OrdersFindManyArgs";
import { OrdersFindUniqueArgs } from "./OrdersFindUniqueArgs";
import { CreateOrdersArgs } from "./CreateOrdersArgs";
import { UpdateOrdersArgs } from "./UpdateOrdersArgs";
import { DeleteOrdersArgs } from "./DeleteOrdersArgs";
import { Customers } from "../../customers/base/Customers";
import { Listings } from "../../listings/base/Listings";
import { OrdersService } from "../orders.service";
@graphql.Resolver(() => Orders)
export class OrdersResolverBase {
  constructor(protected readonly service: OrdersService) {}

  async _ordersItemsMeta(
    @graphql.Args() args: OrdersCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Orders])
  async ordersItems(
    @graphql.Args() args: OrdersFindManyArgs
  ): Promise<Orders[]> {
    return this.service.ordersItems(args);
  }

  @graphql.Query(() => Orders, { nullable: true })
  async orders(
    @graphql.Args() args: OrdersFindUniqueArgs
  ): Promise<Orders | null> {
    const result = await this.service.orders(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Orders)
  async createOrders(@graphql.Args() args: CreateOrdersArgs): Promise<Orders> {
    return await this.service.createOrders({
      ...args,
      data: {
        ...args.data,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,

        listing: args.data.listing
          ? {
              connect: args.data.listing,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Orders)
  async updateOrders(
    @graphql.Args() args: UpdateOrdersArgs
  ): Promise<Orders | null> {
    try {
      return await this.service.updateOrders({
        ...args,
        data: {
          ...args.data,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,

          listing: args.data.listing
            ? {
                connect: args.data.listing,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Orders)
  async deleteOrders(
    @graphql.Args() args: DeleteOrdersArgs
  ): Promise<Orders | null> {
    try {
      return await this.service.deleteOrders(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Customers, {
    nullable: true,
    name: "customer",
  })
  async getCustomer(
    @graphql.Parent() parent: Orders
  ): Promise<Customers | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Listings, {
    nullable: true,
    name: "listing",
  })
  async getListing(@graphql.Parent() parent: Orders): Promise<Listings | null> {
    const result = await this.service.getListing(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
